trigger:
- master

variables:
  - group: 'TMA-Secrets'

stages:
  - stage: BuildApp
    displayName: Build App
    jobs:
    - job: BuildAppJob
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: NodeTool@0  
          inputs:
            versionSpec: '13.x'
        - task: Npm@1
          inputs:
            command: 'install'
        - task: CopyFiles@2
          inputs:
            sourceFolder: '$(Build.SourcesDirectory)'
            contents: '**' 
            targetFolder: $(Build.ArtifactStagingDirectory)
          displayName: 'Copy app files'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifactName: tmaArtifacts
          displayName: 'Publish app artifact'

  # - stage: ValidateInfra
  #   displayName: Validate Infra
  #   jobs:
  #   - deployment: ValidateInfraJob
  #     pool:
  #       vmImage: 'ubuntu-latest'
  #     environment: 'test'
  #     strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - checkout: self
  #             - task: AzureResourceGroupDeployment@2
  #               displayName: 'Azure Deployment:Create Or Update Resource Group action on unpleo-rg'
  #               inputs:
  #                 azureSubscription: tma-sp-001
  #                 resourceGroupName: 'tma-rg-001'
  #                 location: 'South Central US'
  #                 csmFile: 'infra/template.json'
  #                 csmParametersFile: 'infra/parameters.json'
  #                 overrideParameters: -adminPassword $(adminPassword)
  #                 deploymentMode: 'Validation'
  #             - task: AzureResourceGroupDeployment@2
  #               displayName: 'Azure Deployment:Create Or Update Resource Group action on unpleo-rg'
  #               inputs:
  #                 azureSubscription: tma-sp-001
  #                 resourceGroupName: 'tma-rg-001'
  #                 location: 'South Central US'
  #                 csmFile: 'infra/storage.json'
  #                 csmParametersFile: 'infra/storage-parameters.json'
  #                 deploymentMode: 'Validation'

  # - stage: BuildInfra
  #   displayName: Build Infra
  #   jobs:
  #   - deployment: BuildInfraJob
  #     pool:
  #       vmImage: 'ubuntu-latest'
  #     environment: 'development'
  #     strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - checkout: self
  #             - task: AzureResourceGroupDeployment@2
  #               displayName: 'Azure Deployment:Create Or Update Resource Group action on unpleo-rg'
  #               inputs:
  #                 azureSubscription: tma-sp-001
  #                 resourceGroupName: 'tma-rg-001'
  #                 location: 'South Central US'
  #                 csmFile: 'infra/template.json'
  #                 csmParametersFile: 'infra/parameters.json'
  #                 overrideParameters: -adminPassword $(adminPassword)
  #             - task: AzureResourceGroupDeployment@2
  #               displayName: 'Azure Deployment:Create Or Update Resource Group action on unpleo-rg'
  #               inputs:
  #                 azureSubscription: tma-sp-001
  #                 resourceGroupName: 'tma-rg-001'
  #                 location: 'South Central US'
  #                 csmFile: 'infra/storage.json'
  #                 csmParametersFile: 'infra/storage-parameters.json'

  # - stage: SetupInfra
  #   displayName: Setup Infra
  #   jobs:
  #   - deployment: SetupInfraJob
  #     pool:
  #       vmImage: 'ubuntu-latest'
  #     environment: 'setup'
  #     strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - task: AzureCLI@2
  #               displayName: Azure CLI
  #               inputs:
  #                 azureSubscription: tma-sp-001
  #                 scriptType: pscore
  #                 scriptLocation: inlineScript
  #                 inlineScript: |
  #                   az vm run-command invoke -g tma-rg-001 -n tma-vm-001 --command-id RunShellScript --scripts "apt-get update && apt-get install -y sqlite3"            

  - stage: DeployApp
    displayName: Deploy App
    jobs:
    - deployment: DeployAppJob
      pool:
        vmImage: 'windows-latest'
      environment: 'devapp'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureFileCopy@5
                inputs:
                  SourcePath: '$(Pipeline.Workspace)/tmaArtifacts'
                  azureSubscription: 'tma-sp-001'
                  Destination: 'AzureVMs'
                  storage: 'tmavmstorageat001'
                  resourceGroup: 'tma-rg-001'
                  MachineNames: 'tma-vm-001'
                  vmsAdminUserName: 'azureuser'
                  vmsAdminPassword: '$(adminPassword)'
                  TargetPath: '/home/azureuser/tma'
              - task: AzureCLI@2
                displayName: Azure CLI
                inputs:
                  azureSubscription: tma-sp-001
                  scriptType: pscore
                  scriptLocation: inlineScript
                  inlineScript: |
                    az vm run-command invoke -g tma-rg-001 -n tma-vm-001 --command-id RunShellScript --scripts "cd /home/azureuser/tma && npm start"            

  # - stage: DestroyInfra
  #   displayName: Destroy Infra
  #   jobs:
  #   - deployment: DestroyInfraJob
  #     pool:
  #       vmImage: 'ubuntu-latest'
  #     environment: 'destroy'
  #     strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - checkout: self
  #             - task: AzureResourceGroupDeployment@2
  #               displayName: 'Azure Deployment:Create Or Update Resource Group action on unpleo-rg'
  #               inputs:
  #                 azureSubscription: tma-sp-001
  #                 resourceGroupName: 'tma-rg-001'
  #                 location: 'South Central US'
  #                 csmFile: 'infra/cleanup.json'
  #                 deploymentMode: 'Complete'
