trigger:
- master

variables:
  - group: 'TMA-Secrets'

stages:
  - stage: BuildApp
    displayName: Build App
    jobs:
    - job: BuildAppJob
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: NodeTool@0  
          inputs:
            versionSpec: '13.x'
        - task: Npm@1
          inputs:
            command: 'install'
        - task: CopyFiles@2
          inputs:
            sourceFolder: '$(Build.SourcesDirectory)'
            contents: '**' 
            targetFolder: $(Build.ArtifactStagingDirectory)
          displayName: 'Copy app files'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifactName: tmaapp
          displayName: 'Publish app artifact'

  - stage: ValidateInfra
    displayName: Validate Infra
    jobs:
    - deployment: ValidateInfraJob
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'test'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: AzureResourceGroupDeployment@2
                displayName: 'Azure Deployment:Create Or Update Resource Group action on unpleo-rg'
                inputs:
                  azureSubscription: tma-sp-001
                  resourceGroupName: 'tma-rg-001'
                  location: 'South Central US'
                  csmFile: 'infra/template.json'
                  csmParametersFile: 'infra/parameters.json'
                  overrideParameters: -adminPassword $(adminPassword)
                  deploymentMode: 'Validation'

  - stage: BuildInfra
    displayName: Build Infra
    jobs:
    - deployment: BuildInfraJob
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'development'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: AzureResourceGroupDeployment@2
                displayName: 'Azure Deployment:Create Or Update Resource Group action on unpleo-rg'
                inputs:
                  azureSubscription: tma-sp-001
                  resourceGroupName: 'tma-rg-001'
                  location: 'South Central US'
                  csmFile: 'infra/template.json'
                  csmParametersFile: 'infra/parameters.json'
                  overrideParameters: -adminPassword $(adminPassword)

    - stage: SetupInfra
      displayName: Setup Infra
      jobs:
      - deployment: SetupInfraJob
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'setup'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: Azure CLI
                  inputs:
                    azureSubscription: tma-sp-001
                    scriptType: pscore
                    scriptLocation: inlineScript
                    inlineScript: |
                      az vm run-command invoke -g tma-rg-001 -n tma-vm-001 --command-id RunShellScript --scripts "apt-get update && apt-get install -y sqlite3"            

  - stage: DestroyInfra
    displayName: Destroy Infra
    jobs:
    - deployment: DestroyInfraJob
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'destroy'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: AzureResourceGroupDeployment@2
                displayName: 'Azure Deployment:Create Or Update Resource Group action on unpleo-rg'
                inputs:
                  azureSubscription: tma-sp-001
                  resourceGroupName: 'tma-rg-001'
                  location: 'South Central US'
                  csmFile: 'infra/cleanup.json'
                  deploymentMode: 'Complete'
