trigger:
- master

stages:
  - stage: BuildApp
    displayName: Build stage
    jobs:
    - job: BuildJob
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: NodeTool@0  
          inputs:
            versionSpec: '13.x'
        - task: Npm@1
          inputs:
            command: 'install'
        - script: npm start

  - stage: BuildInfra
    displayName: Destroy stage
    jobs:
    - deployment: DestroyJob
      pool:
        vmImage: 'ubuntu-20.04'
      environment: 'development'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self


