trigger:
- master

variables:
  - group: 'TMA-Secrets'

stages:
  - stage: BuildApp
    displayName: Build App
    jobs:
    - job: BuildAppJob
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: NodeTool@0  
          inputs:
            versionSpec: '13.x'
        - task: Npm@1
          inputs:
            command: 'install'

  - stage: ValidateInfra
    displayName: Validate Infra
    jobs:
    - deployment: ValidateInfraJob
      pool:
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: AzureResourceGroupDeployment@2
                displayName: 'Azure Deployment:Create Or Update Resource Group action on unpleo-rg'
                inputs:
                  azureSubscription: tma-sp-001
                  resourceGroupName: 'tma-rg-001'
                  location: 'South Central US'
                  csmFile: 'infra/template.json'
                  csmParametersFile: 'infra/parameters.json'
                  overrideParameters: -adminPassword $(adminPassword)
                  deploymentMode: 'Validation'

  - stage: BuildInfra
    displayName: Build Infra
    jobs:
    - deployment: BuildInfraJob
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'development'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: AzureResourceGroupDeployment@2
                displayName: 'Azure Deployment:Create Or Update Resource Group action on unpleo-rg'
                inputs:
                  azureSubscription: tma-sp-001
                  resourceGroupName: 'tma-rg-001'
                  location: 'South Central US'
                  csmFile: 'infra/template.json'
                  csmParametersFile: 'infra/parameters.json'
                  overrideParameters: -adminPassword $(adminPassword)
