trigger:
- master

stages:
  - stage: BuildApp
    displayName: Build stage
    jobs:
    - job: BuildJob
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - script: apk add --no-cache
        - task: Npm@1
          inputs:
            command: 'install'
        - task: Npm@1
          inputs:
            command: 'start'

  - stage: BuildInfra
    displayName: Destroy stage
    jobs:
    - deployment: DestroyJob
      pool:
        vmImage: 'ubuntu-20.04'
      environment: 'development'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self


